
const typeGlobal = {
    CHANGE_GLOBAL_STATE_SELECTION:"CHANGE_GLOBAL_STATE_SELECTION",
    CHANGE_GLOBAL_STATE_MODAL:"CHANGE_GLOBAL_STATE_MODAL",
    CHANGE_GLOBAL_STATE_MODAL_ALERT:"CHANGE_GLOBAL_STATE_MODAL_ALERT"
}

export default typeGlobal;