
const typePersonalInformation = {
   STATE_COMBOBOX_GENDER:"STATE_COMBOBOX_GENDER",
   STATE_COMBOBOX_DATA_OF_BIRTH:"STATE_COMBOBOX_DATA_OF_BIRTH",
   STATE_INPUT_NAME:"STATE_INPUT_NAME",
   STATE_INPUT_LAST_NAME:"STATE_INPUT_LAST_NAME",
   STATE_INPUT_AGE:"STATE_INPUT_AGE",
   STATE_INPUT_DATE_OF_BIRTH:"STATE_INPUT_DATE_OF_BIRTH",
   STATE_COMBOBOX_GENDER_SELECTION:"STATE_COMBOBOX_GENDER_SELECTION",
   STATE_COMBOBOX_CIVIL_STATUS_SELECTION:"STATE_COMBOBOX_CIVIL_STATUS_SELECTION",
 
}

export default typePersonalInformation;