const shipmentInformation = {
  STATE_INPUT_COUNTRY: "STATE_INPUT_COUNTRY",
  STATE_INPUT_CITY: "STATE_INPUT_CITY",
  STATE_INPUT_ADDRESS: "STATE_INPUT_ADDRESS",
  STATE_INPUT_POSTAL_CODE: "STATE_INPUT_POSTAL_CODE",
};

export default shipmentInformation;
